FROM node:16

WORKDIR /usr/src/app

ARG CLOUDINARY_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG CLOUDINARY_USER_AVATARS_PRESET_NAME
ARG CLOUDINARY_USER_AVATARS_FOLDER_NAME
ARG AUTH0_DOMAIN
ARG AUTH0_API_URL
ARG AUTH0_CLIENT_ID
ARG GRAPHQL_URL
ARG AUTH0_API_TOKEN

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build
