FROM node:16

WORKDIR /usr/src/app

ENV CLOUDINARY_NAME=${CLOUDINARY_NAME}
ENV CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ENV CLOUDINARY_USER_AVATARS_PRESET_NAME=${CLOUDINARY_USER_AVATARS_PRESET_NAME}
ENV CLOUDINARY_USER_AVATARS_FOLDER_NAME=${CLOUDINARY_USER_AVATARS_FOLDER_NAME}
ENV AUTH0_DOMAIN=${AUTH0_DOMAIN}
ENV AUTH0_API_URL=${AUTH0_API_URL}
ENV AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
ENV GRAPHQL_URL=${GRAPHQL_URL}
ENV AUTH0_API_TOKEN=${AUTH0_API_TOKEN}

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build
